### ISSUE TITLE
Error: undefined symbol: _dl_sym

### ISSUE THREAD

**Issue by nm17** [wpbrown/openssl-keylog#1]
```
*** HOOKED_SSLKEYLOGFILE set to /tmp/sslkeylogged-k6feDI1D.keys ***
./XXXXX: symbol lookup error: /XXXXX/openssl-keylog/libsslkeylog.so: undefined symbol: _dl_sym
```

**Comment by nm17** [comment]
ldd (Ubuntu GLIBC 2.35-0ubuntu3) 2.35

**Comment by wpbrown** [comment]
I guess this is Ubuntu 22.04 based on the glibc version? Something has changed in the exported symbols of glibc. I need to investigate.

**Comment by nm17** [comment]
@wpbrown yes, I use Ubuntu 22.04. Sorry for not saying this earlier!

**Comment by ngg** [comment]
`_dl_sym` is not exported from glibc since 2.34, see https://github.com/bminor/glibc/commit/7a5db2e82fbb6c3a6e3fdae02b7166c5d0e8c7a8

**Comment by wpbrown** [comment]
Thank you. I saw that. I haven't found a workaround yet, more investigation will be necessary. This is being hooked to deal with how .NET runtime dynamically resolves dl functions. Most applications don't actually need this.

**Comment by wpbrown** [comment]
Fixed on `main`
