### ISSUE TITLE
sslkeylogged encounters invalid pointer

### ISSUE THREAD

**Issue by iinuwa** [wpbrown/openssl-keylog#4]
When I run `sslkeylogged` on Ubuntu 22.04, I get this error:

```
> sslkeylogged ./bin/Debug/net6.0/MyProgram
*** HOOKED_SSLKEYLOGFILE set to /tmp/sslkeylogged-lPX8yY5L.keys ***
munmap_chunk(): invalid pointer
fish: Job 1, 'sslkeylogged ./bin/Debug/net6.0…' terminated by signal SIGABRT (Abort)
```

I'm not sure what this means, but it doesn't seem like the TLS connection can be established.

**Comment by wpbrown** [comment]
It means there was memory corruption, but there is no dynamic memory mgmt in the library. I am unable to reproduce this on .NET 6 + Ubuntu 22.04.
